In [3]:
import numpy as np

# Creating arrays

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [11]:
a = np.array([1,2,3,4,12])

In [12]:
a

array([ 1,  2,  3,  4, 12])

In [14]:
a[2] ## busco el elemento en la posición 3, porque arranca en 0

np.int64(3)

In [15]:
a[2] = 10 ## cambio el valor

In [16]:
a

array([ 1,  2, 10,  4, 12])

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [21]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multidimensional array

In [23]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [25]:
n=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]    
])

In [26]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
n[0,1]

np.int64(2)

In [28]:
n[0,1] = 20

In [29]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [30]:
n [0]

array([ 1, 20,  3])

In [31]:
n [2] = [1,1,1]

In [32]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [35]:
n[:1]

array([[ 1, 20,  3]])

In [36]:
n[:,1]

array([20,  5,  1])

## Random gerated arrays

In [42]:
np.random.seed(2)
100 * np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [41]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [43]:
np.random.seed(2)
np.random.randint(low=0,high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element-wise operation 

In [45]:
a =  np. arange(5)
a

array([0, 1, 2, 3, 4])

In [46]:
a+1

array([1, 2, 3, 4, 5])

In [47]:
a*2

array([0, 2, 4, 6, 8])

In [53]:
b = (10 + (a*2))**2 /100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [54]:
a+b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [55]:
a*b

array([ 0.  ,  1.44,  3.92,  7.68, 12.96])

## Comparison operations

In [57]:
a >= 2

array([False, False,  True,  True,  True])

In [58]:
a > b

array([False, False,  True,  True,  True])

In [59]:
a[a > b]

array([2, 3, 4])

## Sumarizing Operations

In [60]:
a.sum()

np.int64(10)

In [61]:
a

array([0, 1, 2, 3, 4])

In [62]:
a.mean()

np.float64(2.0)

In [63]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [64]:
n.sum()

np.int64(42)

In [65]:
n.min()

np.int64(1)